import { ApiProperty } from '@nestjs/swagger';
import {
  IsNotEmpty,
  IsString,
  IsOptional,
  IsBoolean,
  IsArray,
  ArrayNotEmpty,
} from 'class-validator';

export class CreateScheduleRuleDto {
  @ApiProperty({ example: '4 on / 3 off pattern' })
  @IsString()
  @IsNotEmpty()
  name: string;

  // Free-form pattern or will be autogenerated from the shiftTypes / dates below
  @ApiProperty({ example: '4on-3off', required: false })
  @IsOptional()
  @IsString()
  pattern?: string;

  @ApiProperty({ example: ['Normal', 'Rotational'], required: false })
  @IsOptional()
  @IsArray()
  @ArrayNotEmpty()
  shiftTypes?: string[];

  @ApiProperty({ example: '2025-11-01', required: false })
  @IsOptional()
  @IsString()
  startDate?: string;

  @ApiProperty({ example: '2025-12-01', required: false })
  @IsOptional()
  @IsString()
  endDate?: string;

  @ApiProperty({ example: true, required: false })
  @IsOptional()
  @IsBoolean()
  active?: boolean;
}
